### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [gwcoffey/j-w-von-goethe_the-sorrows-of-young-werther_r-d-boylan#5]
- Replace em-dashes with `--` in metadata `<dc:subject>`s
- Run `clean` to convert long-description to escaped XHTML
- Our own `se:subjects` are meant to be fairly broad, not as specific as where you went; more like bookstore aisles than anything. I think just `fiction` alone will be sufficient.  I have yet to make a complete categorization of our subject tags.
- "de-DE" -> "de" in long-description
- Typo: Storm and Sress
- Typo: it’s genisis -> its genesis
- Typo: ehchanting
- `#transcriber-1` seems to be incorrect

**Comment by acabal** [comment]
Since we have an endnotes file, we also need the `ann` MARC relator tag on whoever was the annotator. Same for the writer of the preface (this looks like Goethe but we have to add that relator tag to him anyway), and the PG transcription indicates there was an editor, Nathen Haskell Dole, who also has to be added.

**Comment by gwcoffey** [comment]
@acabal fyi, clean did not encode the description. Is that a bug only on macOS maybe? I can investigate further but I thought I'd let you know. For now I'll clean it up by hand.

**Comment by acabal** [comment]
`clean` will only do that if you escape the HTML in a `<![CDATA[ ... ]]>` tag.  So all you have to do is include that tag, which will contain actual HTML, then run `clean` which will remove the CDATA portion and escape the HTML.

**Comment by acabal** [comment]
Also, I see you included Goethe twice, one more as the writer of the preface.  But, we don't have to include all the data again; all you have to do is add an additional `<meta property="role" refines="#author" scheme="marc:relators">wpr</meta>` to the existing author metadata block.  Can you take update it?
